# Data Workflow Lab 1

Clean and summarize Project 3 data.

### Learning Objectives

* Practice text cleaning techniques
* Practice datatype conversion
* Practice filling in missing values with either 0 or the average in the column
* Practice categorical data techniques
* Transform data into usable quantities

In [ ]:
% matplotlib inline
import datetime
import numpy as np
import pandas as pd

# import the plotting functions:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import plotly.plotly as py

In [179]:
# Load the data
df = pd.read_csv("Iowa_Liquor_sales_sample_10pct.csv")
print df.columns
print df.dtypes
print df.shape # num of rows and columns
df.head()

Index([u'Date', u'Store Number', u'City', u'Zip Code', u'County Number',
       u'County', u'Category', u'Category Name', u'Vendor Number',
       u'Item Number', u'Item Description', u'Bottle Volume (ml)',
       u'State Bottle Cost', u'State Bottle Retail', u'Bottles Sold',
       u'Sale (Dollars)', u'Volume Sold (Liters)', u'Volume Sold (Gallons)'],
      dtype='object')
Date                      object
Store Number               int64
City                      object
Zip Code                  object
County Number            float64
County                    object
Category                 float64
Category Name             object
Vendor Number              int64
Item Number                int64
Item Description          object
Bottle Volume (ml)         int64
State Bottle Cost         object
State Bottle Retail       object
Bottles Sold               int64
Sale (Dollars)            object
Volume Sold (Liters)     float64
Volume Sold (Gallons)    float64
dtype: object
(270955, 18)

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,11/04/2015,3717,SUMNER,50674,9.0,Bremer,1051100.0,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,$4.50,$6.75,12,$81.00,9.0,2.38
1,03/02/2016,2614,DAVENPORT,52807,82.0,Scott,1011100.0,BLENDED WHISKIES,395,27605,Tin Cup,750,$13.75,$20.63,2,$41.26,1.5,0.40
2,02/11/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1011200.0,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,$12.59,$18.89,24,$453.36,24.0,6.34
3,02/03/2016,2501,AMES,50010,85.0,Story,1071100.0,AMERICAN COCKTAILS,395,59154,1800 Ultimate Margarita,1750,$9.50,$14.25,6,$85.50,10.5,2.77
4,08/18/2015,3654,BELMOND,50421,99.0,Wright,1031080.0,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,$7.20,$10.80,12,$129.60,21.0,5.55

1. The original dataset from iowa.gov has 24 columns and 10.3M rows. This reduced dataset has 18 columns and 270955 rows. The following columns have been removed from the original 24 columns - invoice #, store name, address,store location,vendor name,pack
2. The datatypes of these 4 columns need to be changed - Date(DateTime),State Bottle Cost(float),State Bottle Retail(float), Sale(float).
3. Volume Sold (Gallons) can be removed- it is a redundant column derived from volume Sold (Litres) column.

## Clean the data

Let's practice our data cleaning skills on the Project 3 dataset. If you don't remember how to do any of these tasks, look back at your work from the previous weeks or search the internet. There are many blog articles and Stack Overflow posts that cover these topics.

You'll want to complete at least the following tasks:
* Remove redundant columns
* Remove "$" prices from characters and convert values to floats.
* Convert dates to pandas datetime objects
* Convert category floats to integers
* Drop or fill in bad values

In [180]:
# Remove redundant columns
# the column 'Volume SOld (Gallons) has been deleted
df.head()
df.shape

(270955, 18)

In [195]:
# Another method of finding redundant columns is to plot pairplot between the variables 
#and remove all those plots that have straight lines.

In [200]:
# Remove $ from certain columns
#df['State Bottle Cost'] = df['State Bottle Cost'].str.replace('$','')
#df['State Bottle Retail'] = df['State Bottle Retail'].str.replace('$','')
#df['Sale (Dollars)'] = df['Sale (Dollars)'].str.replace('$','')

In [182]:
# Convert dates to datetime format

df["Date"] = pd.to_datetime(df["Date"])

# Convert State Bottle Cost, State Bottle Retail, Sale (Dollars) to float format

df['State Bottle Cost'] = df['State Bottle Cost'].astype('float')
df['State Bottle Retail'] = df['State Bottle Retail'].astype('float')
df['Sale (Dollars)'] = df['Sale (Dollars)'].astype('float')

In [183]:
df.get_dtype_counts()

datetime64[ns]    1
float64           7
int64             5
object            5
dtype: int64

In [184]:
# Drop or replace bad values

# Finding the number of null values in each column
columns = [df.columns]
for item in columns:
    print(df[item].isnull().sum())

# Convert integers
df['Bottle Volume (ml)'] = df['Bottle Volume (ml)'].astype('float')
df['Bottles Sold'] = df['Bottles Sold'].astype('float')
df.get_dtype_counts()

Date                        0
Store Number                0
City                        0
Zip Code                    0
County Number            1077
County                   1077
Category                   68
Category Name             632
Vendor Number               0
Item Number                 0
Item Description            0
Bottle Volume (ml)          0
State Bottle Cost           0
State Bottle Retail         0
Bottles Sold                0
Sale (Dollars)              0
Volume Sold (Liters)        0
Volume Sold (Gallons)       0
dtype: int64

datetime64[ns]    1
float64           9
int64             3
object            5
dtype: int64

In [185]:
# all the rows with null values - total of 1697(using shape)
df_missing_values = df[pd.isnull(df).any(axis=1)]
df_missing_values

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
135,2016-01-20,5222,CEDAR RAPIDS,52402,NaN,NaN,1051010.0,AMERICAN GRAPE BRANDIES,115,53214,Paul Masson Grande Amber Brandy,375.0,3.22,4.83,24.0,115.92,9.00,2.38
198,2016-03-02,3820,SIOUX CITY,51103,NaN,NaN,1032080.0,IMPORTED VODKA,35,34359,Grey Goose Vodka,200.0,5.00,7.50,12.0,90.00,2.40,0.63
272,2016-03-21,4222,EVANSDALE,50707,NaN,NaN,1062300.0,FLAVORED RUM,370,42716,Malibu Coconut Rum,750.0,7.49,11.24,3.0,33.72,2.25,0.59
290,2016-03-21,5236,ANAMOSA,52205,NaN,NaN,1081600.0,WHISKEY LIQUEUR,421,64868,Fireball Cinnamon Whiskey,1750.0,15.33,23.00,6.0,138.00,10.50,2.77
321,2016-02-23,4203,WAVERLY,50677,NaN,NaN,1051100.0,APRICOT BRANDIES,434,55084,Paramount Blackberry Brandy,375.0,3.55,5.33,24.0,127.92,9.00,2.38
863,2016-01-11,2460,HAMPTON,50441,NaN,NaN,1011200.0,STRAIGHT BOURBON WHISKIES,461,77776,Wild Turkey American Honey,750.0,10.50,15.75,3.0,47.25,2.25,0.59
896,2015-02-05,4829,DES MOINES,50314,77.0,Polk,1022200.0,NaN,85,3657,Herradura Gold Reposado 6pak,750.0,23.58,35.37,6.0,212.22,4.50,1.19
901,2016-02-25,4647,WATERLOO,50707,7.0,Black Hawk,1052100.0,NaN,420,48099,Hennessy VS,200.0,5.74,8.61,24.0,206.64,4.80,1.27
964,2015-05-19,4247,BELMOND,50421,NaN,NaN,1012100.0,CANADIAN WHISKIES,55,12408,Canadian Ltd Whisky,1750.0,9.14,13.71,6.0,82.26,10.50,2.77
982,2016-03-30,5222,CEDAR RAPIDS,52402,NaN,NaN,1031080.0,VODKA 80 PROOF,300,36904,Mccormick Vodka Pet,375.0,1.80,2.70,24.0,64.80,9.00,2.38
1024,2016-03-23,3820,SIOUX CITY,51103,NaN,NaN,1081390.0,IMPORTED SCHNAPPS,421,69637,Dr. Mcgillicuddy's Cherry Schnapps,1000.0,11.00,16.50,24.0,396.00,24.00,6.34
1514,2016-02-18,2515,MASON CITY,50401,17.0,Cerro Gordo,1082100.0,NaN,420,67487,Grand Marnier Raspberry Peach,750.0,23.31,34.97,2.0,69.94,1.50,0.40
1630,2016-02-10,5224,CORALVILLE,52241,NaN,NaN,1062310.0,SPICED RUM,260,43337,Captain Morgan Spiced Rum,1000.0,11.75,17.63,12.0,211.56,12.00,3.17
1667,2016-03-30,2637,DAVENPORT,52804,NaN,NaN,1041100.0,AMERICAN DRY GINS,260,30318,Gordon's Gin London Dry - Pet,1750.0,11.00,16.50,6.0,99.00,10.50,2.77
1684,2016-02-08,3747,SIGOURNEY,52591,54.0,Keokuk,1052100.0,NaN,420,48106,Hennessy Vs Cognac,750.0,18.99,28.49,2.0,56.98,1.50,0.40
1798,2016-03-03,5227,CLINTON,52732,NaN,NaN,1031080.0,VODKA 80 PROOF,297,35926,Five O'clock PET Vodka,750.0,3.37,5.06,12.0,60.72,9.00,2.38
2084,2016-03-24,5229,NORWALK,50211,NaN,NaN,1012100.0,CANADIAN WHISKIES,260,11296,Crown Royal,750.0,15.00,22.50,12.0,270.00,9.00,2.38
2176,2016-03-21,5236,ANAMOSA,52205,NaN,NaN,1031080.0,VODKA 80 PROOF,55,37938,Skol Vodka,1750.0,7.11,10.67,2.0,21.34,3.50,0.92
2203,2016-02-16,4589,SIBLEY,51249,72.0,Osceola,1032100.0,NaN,115,34821,Svedka Vodka,1750.0,14.74,22.11,2.0,44.22,3.50,0.92
2533,2016-03-09,2637,DAVENPORT,52804,NaN,NaN,1062200.0,PUERTO RICO & VIRGIN ISLANDS RUM,434,45278,Paramount White Rum,1750.0,7.84,11.76,6.0,70.56,10.50,2.77
2549,2016-03-22,5210,CLARINDA,51632,NaN,NaN,1022100.0,TEQUILA,35,89099,Cazadores Anejo,750.0,23.33,35.00,1.0,35.00,0.75,0.20
2678,2016-03-29,5210,CLARINDA,51632,NaN,NaN,1012100.0,CANADIAN WHISKIES,65,10627,Canadian Club Whisky,1000.0,9.71,14.57,12.0,174.84,12.00,3.17
2871,2015-09-22,4247,BELMOND,50421,NaN,NaN,1062300.0,FLAVORED RUM,65,44428,Cruzan Blueberry Lemonade,750.0,6.83,10.25,1.0,10.25,0.75,0.20
2894,2016-02-09,2413,DUBUQUE,52001,31.0,Dubuque,1082100.0,NaN,130,64136,Disaronno Amaretto,750.0,13.86,20.79,12.0,249.48,9.00,2.38
3071,2016-02-15,2539,IOWA FALLS,50126,42.0,Hardin,1052100.0,NaN,420,48106,Hennessy Vs Cognac,750.0,18.99,28.49,3.0,85.47,2.25,0.59
3246,2016-03-16,3820,SIOUX CITY,51103,NaN,NaN,1032080.0,IMPORTED VODKA,260,36871,Ciroc Luxury Vodka,750.0,18.49,27.74,1.0,27.74,0.75,0.20
3482,2016-02-10,3524,AMES,50010,85.0,Story,1032100.0,NaN,115,34821,Svedka Vodka,1750.0,14.74,22.11,6.0,132.66,10.50,2.77
3939,2016-03-21,5236,ANAMOSA,52205,NaN,NaN,1022100.0,TEQUILA,434,87937,Juarez Tequila Silver,1000.0,6.92,10.38,12.0,124.56,12.00,3.17
4015,2016-03-16,2637,DAVENPORT,52804,NaN,NaN,1081330.0,PEACH SCHNAPPS,65,82844,Dekuyper Peachtree Schnapps,375.0,3.07,4.61,4.0,18.44,1.50,0.40
4448,2015-03-03,4247,BELMOND,50421,NaN,NaN,1031080.0,VODKA 80 PROOF,380,37338,UV Vodka PET,1750.0,10.49,15.99,6.0,95.94,10.50,2.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265904,2016-02-18,2248,DES MOINES,50312,77.0,Polk,1052100.0,NaN,420,48105,Hennessy VS,375.0,9.99,14.99,4.0,59.96,1.50,0.40
266383,2015-09-08,4247,BELMOND,50421,NaN,NaN,1031080.0,VODKA 80 PROOF,297,35916,Five O'clock Vodka,750.0,3.37,5.06,12.0,60.72,9.00,2.38
266646,2015-12-17,2633,DES MOINES,50320,77.0,Polk,1091100.0,NaN,434,933934,Pearl Caramel,1000.0,8.67,13.01,24.0,312.24,24.00,6.34
266660,2016-03-02,3820,SIOUX CITY,51103,NaN,NaN,1081900.0,MISC. AMERICAN CORDIALS & LIQUEURS,65,85526,Dekuyper Signature Blue Curacao,750.0,5.25,7.88,24.0,189.12,18.00,4.76
266801,2016-03-03,5220,MASON CITY,50401,NaN,NaN,1031080.0,VODKA 80 PROOF,434,36308,Hawkeye Vodka,1750.0,7.17,10.76,6.0,64.56,10.50,2.77
266806,2016-03-22,4006,LARCHWOOD,51241,NaN,NaN,1012100.0,CANADIAN WHISKIES,65,15248,Windsor Canadian Pet,1750.0,9.45,14.18,6.0,85.08,10.50,2.77
266852,2016-02-23,4167,DUBUQUE,52001,31.0,Dubuque,1052100.0,NaN,420,48105,Hennessy VS,375.0,9.99,14.99,72.0,1079.28,27.00,7.13
266961,2016-03-21,2650,HARLAN,51537,NaN,NaN,1011100.0,BLENDED WHISKIES,65,22784,Beam's 8 Star Bl Whiskey,375.0,2.09,3.14,4.0,12.56,1.50,0.40
267727,2016-02-23,4712,DUBUQUE,52001,31.0,Dubuque,1052100.0,NaN,420,48105,Hennessy VS,375.0,9.99,14.99,2.0,29.98,0.75,0.20
267729,2016-03-07,2650,HARLAN,51537,NaN,NaN,1011200.0,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000.0,12.59,18.89,12.0,226.68,12.00,3.17
268016,2016-02-17,2596,OTTUMWA,52501,90.0,Wapello,1052100.0,NaN,420,48106,Hennessy Vs Cognac,750.0,18.99,28.49,1.0,28.49,0.75,0.20
268130,2016-02-22,4794,BURLINGTON,52601,29.0,Des Moines,1032100.0,NaN,277,34746,Stolichnaya Premium Vodka 80 Prf,750.0,11.99,17.99,12.0,215.88,9.00,2.38
268186,2016-02-08,5214,CEDAR RAPIDS,52404,NaN,NaN,1011200.0,STRAIGHT BOURBON WHISKIES,65,19476,Maker's Mark,750.0,17.32,25.98,12.0,311.76,9.00,2.38
268475,2016-02-16,5230,CEDAR RAPIDS,52402,NaN,NaN,1032200.0,IMPORTED VODKA - MISC,260,64572,Ciroc Pineapple,375.0,9.25,13.88,4.0,55.52,1.50,0.40
268504,2016-02-23,4247,BELMOND,50421,NaN,NaN,1062310.0,SPICED RUM,260,43418,Captain Morgan Tattoo,750.0,9.00,13.50,2.0,27.00,1.50,0.40
269000,2016-01-25,2460,HAMPTON,50441,NaN,NaN,1031080.0,VODKA 80 PROOF,260,37418,Popov Vodka 80 Prf,1750.0,8.50,12.75,6.0,76.50,10.50,2.77
269080,2016-03-22,5230,CEDAR RAPIDS,52402,NaN,NaN,1701100.0,DECANTERS & SPECIALTY PACKAGES,65,36409,Effen Football Sleeve,750.0,18.89,28.34,1.0,28.34,0.75,0.20
269414,2016-03-16,4169,DES MOINES,50317,NaN,NaN,1031200.0,VODKA FLAVORED,205,40289,New Amsterdam Coconut,750.0,6.90,10.35,2.0,20.70,1.50,0.40
269449,2016-03-23,2637,DAVENPORT,52804,NaN,NaN,1011300.0,TENNESSEE WHISKIES,85,26585,Gentleman Jack,375.0,6.55,9.83,2.0,19.66,0.75,0.20
269457,2015-10-19,2633,DES MOINES,50320,77.0,Polk,1022200.0,NaN,85,3657,Herradura Gold Reposado 6pak,750.0,23.58,35.37,6.0,212.22,4.50,1.19
269482,2016-03-01,5210,CLARINDA,51632,NaN,NaN,1012210.0,SINGLE MALT SCOTCH,260,5696,Oban Single Malt Scotch,750.0,40.50,60.75,1.0,60.75,0.75,0.20
269715,2016-03-16,2637,DAVENPORT,52804,NaN,NaN,1081200.0,CREAM LIQUEURS,962,80143,Forbidden Secret Dark Mocha,750.0,11.79,17.69,6.0,106.14,4.50,1.19
269751,2016-02-17,5128,DES MOINES,50310,77.0,Polk,1032100.0,NaN,115,34821,Svedka Vodka,1750.0,14.74,22.11,6.0,132.66,10.50,2.77
269885,2016-02-04,4648,WATERLOO,50703,7.0,Black Hawk,1052100.0,NaN,420,48106,Hennessy Vs Cognac,750.0,18.99,28.49,12.0,341.88,9.00,2.38
269953,2015-11-30,4229,HARLAN,51537,83.0,Shelby,NaN,NaN,255,297,Templeton Rye w/Flask,750.0,18.09,27.14,12.0,325.68,9.00,2.38
269982,2016-02-22,2460,HAMPTON,50441,NaN,NaN,1081600.0,WHISKEY LIQUEUR,259,86626,Cold Spell Mint,750.0,7.47,11.21,2.0,22.42,1.50,0.40
270031,2015-05-12,4247,BELMOND,50421,NaN,NaN,1081390.0,IMPORTED SCHNAPPS,421,69667,Dr. Mcgillicuddy's Vanilla,1000.0,11.00,16.50,1.0,16.50,1.00,0.26
270046,2016-02-17,2637,DAVENPORT,52804,82.0,Scott,1082100.0,NaN,420,65126,Grand Marnier Cordon Rouge,750.0,23.31,34.97,4.0,139.88,3.00,0.79
270083,2016-03-21,5236,ANAMOSA,52205,NaN,NaN,1052010.0,IMPORTED GRAPE BRANDIES,420,48164,Hennessy VSOP Privilege,750.0,29.99,44.99,1.0,44.99,0.75,0.20
270654,2016-02-17,2572,CEDAR FALLS,50613,7.0,Black Hawk,1032100.0,NaN,277,34746,Stolichnaya Premium Vodka 80 Prf,750.0,11.99,17.99,2.0,35.98,1.50,0.40

In [186]:
#number of unique store numbers
print len(df['Store Number'].unique())
print len(df['City'].unique())
print len(df['Zip Code'].unique())
print len(df['County Number'].unique())

1400
385
415
100

In [204]:
# get all the cities with null values in county
city = df['City'].groupby(df['Zip Code'])

In [207]:
df[['Bottle Volume (ml)','State Bottle Cost', 'State Bottle Retail', 'Bottles Sold',
       'Sale (Dollars)', 'Volume Sold (Liters)']].describe()

,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters)
count,270955.000000,270955.000000,270955.000000,270955.000000,270955.000000,270955.000000
mean,924.830341,9.773281,14.675760,9.871285,128.902375,8.981351
std,493.088489,7.047119,10.570145,24.040912,383.027369,28.913690
min,50.000000,0.890000,1.340000,1.000000,1.340000,0.100000
25%,750.000000,5.500000,8.270000,2.000000,30.450000,1.500000
50%,750.000000,8.000000,12.270000,6.000000,70.560000,5.250000
75%,1000.000000,11.920000,17.880000,12.000000,135.000000,10.500000
max,6000.000000,425.000000,637.500000,2508.000000,36392.400000,2508.000000

## Filter the Data

Some stores may have opened or closed in 2015. These data points will heavily skew our models, so we need to filter them out or find a way to deal with them.

You'll need to provide a summary in your project report about these data points. You may also consider using the monthly sales in your model and including other information (number of months or days each store is open) in your data to handle these unusual cases.

Let's record the first and last sales dates for each store. We'll save this information for later when we fit our models.

In [188]:
# Determine which stores were open all of 2015
# Find the first and last sales date.


# Filter out stores that opened or closed throughout the year
# You may want to save this step until you start modelling

## Compute New Columns and Tables

Since we're trying to predict sales and/or profits, we'll want to compute some intermediate data. There are a lot of ways to do thisand good use of pandas is crucial. For example, for each transaction we may want to know:
* margin, retail cost minus bottle cost
* price per bottle
* price per liter

We'll need to make a new dataframe that indexes quantities by store:
* sales per store for all of 2015
* sales per store for Q1 2015
* sales per store for Q1 2016
* total volumes sold
* mean transaction revenue, gross margin, price per bottle, price per liter, etc.
* average sales per day
* number of days open

Make sure to retain other variables that we'll want to use to build our models, such as zip code, county number, city, etc. We recommend that you spend some time thinking about the model you may want to fit and computing enough of the suggested quantities to give you a few options.

Bonus tasks:
* Restrict your attention to stores that were open for all of 2015 and Q1 2016. Stores that opened or closed in 2015 will introduce outliers into your data.
* For each transaction we have the item category. You may be able to determine the store type (primarily wine, liquor, all types of alcohol, etc.) by the most common transaction category for each store. This could be a useful categorical variable for modelling.

In [189]:
# Margin and Price per liter

In [190]:
# Sales per store, 2015

# Filter by our start and end dates
df.sort_values(by=["Store Number", "Date"], inplace=True)
start_date = pd.Timestamp("20150101")
end_date = pd.Timestamp("20151231")
mask = (df['Date'] >= start_date) & (df['Date'] <= end_date)
sales = df[mask]

# Group by store name
sales = sales.groupby(by=["Store Number"], as_index=False)
# Compute sums, means
sales = sales.agg({"Sale (Dollars)": [np.sum, np.mean],
                   "Volume Sold (Liters)": [np.sum, np.mean],
                   "Margin": np.mean,
                   "Price per Liter": np.mean,
                   "Zip Code": lambda x: x.iloc[0], # just extract once, should be the same
                   "City": lambda x: x.iloc[0],
                   "County Number": lambda x: x.iloc[0]})
# Collapse the column indices
sales.columns = [' '.join(col).strip() for col in sales.columns.values]
# Rename columns

# Quick check
sales.head()

KeyError: 'Price per Liter'

In [ ]:
# Q1 sales, may want to also use aggregate as above to have more columns (means, etc.)

# Sales 2015  Q1

# Sales 2016 Q1

Proceed with any calculations that you need for your models, such as grouping
sales by zip code, most common vendor number per store, etc. Once you have finished adding columns, be sure to save the dataframe.

In [ ]:
# Compute more things
# ...

In [ ]:
# Save this dataframe

# Let's add the dates computed above to this data.
sales["First Date"] = dates['Date amin']
sales["Last Date"] = dates['Date amax']

sales.to_csv("sales.csv")